[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
factorize = "6YWgPX8CbreGMdPAkCnXxLG5xW9T8LiTQHqafP3C3GhT"

[programs.devnet]
factorize = "6YWgPX8CbreGMdPAkCnXxLG5xW9T8LiTQHqafP3C3GhT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run test:anchor"
